sudo: required
services:
  - docker

before_install:
  -  docker build -t pereter92/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pereter92/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "petro-tarasenko-docker-setup"
  env: "Petrotarasenkodockersetup-env"
  bucket_name: "elasticbeanstalk-us-west-2-638627384021"
  bucket_path: "petro-tarasenko-docker-setup"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY